before_commands:
    - "composer install --no-dev --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 600

    php_code_coverage:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]

    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]

    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]

    php_loc:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]

    php_mess_detector:
        config:
            code_size_rules:
                cyclomatic_complexity: true
            unused_code_rules:
                unused_local_variable: true
                unused_private_method: true
                unused_formal_parameter: true

    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]

    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]

    sensiolabs_security_checker: true

    php_hhvm:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
